version: "3.5"
services:
  stacks-blockchain:
    image: blockstack/stacks-blockchain:${STACKS_BLOCKCHAIN_VERSION:-latest}
    container_name: stacks-blockchain
    restart: on-failure
    ports:
      - ${STACKS_CORE_RPC_PORT:-20443}:${STACKS_CORE_RPC_PORT:-20443}
      - ${STACKS_CORE_P2P_PORT:-20444}:${STACKS_CORE_P2P_PORT:-20444}
      - ${NODE_METRICS_PORT:-9153}:${NODE_METRICS_PORT:-9153}
    env_file:
      - ${SCRIPTPATH}/.env
    networks:
      - default
    profiles:
      - stacks-blockchain
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
networks:
  default:
    name: ${DOCKER_NETWORK}
    ipam:
      driver: default
